#custom build flags
flags = ['-g', '-O2', '-march=native', '-Wall', '-W' ]

#setup libraries to link and paths
libs=['hdf5_hl_cpp','hdf5_cpp']

include=['../include']

#define build environment
env = Environment()
warnEnv = env.Clone(LIBS=libs, CXXFLAGS=flags, CPPPATH=include)

writeProgram = warnEnv.Program(target='write', source=['write.cpp']);
readProgram = warnEnv.Program(target='read', source=['read.cpp']);


warnEnv.Depends(writeProgram, Glob('../include/*'))
warnEnv.Depends(readProgram, Glob('../include/*'))

warnEnv.Clean('.', Glob('*.h5'));

