#!/usr/bin/ruby 

require 'ftools'

user = ENV['USER']
Dir.chdir("..")
root = Dir.pwd

#remove temps from include/
Dir.chdir("#{root}/include")
system("rm -f *~")

if user == "root"
  #create dirs if they don't exist
  File.makedirs '/usr/local/include/HDF5'
  Dir.chdir('/usr/local/include/HDF5')
  #remove the current set of files
  Dir.foreach('./') { |x|
    if(x!='.' and x!='..')
      File.delete("#{x}")
    end
  }
  Dir.chdir("/usr/local/include/HDF5")
  path = "#{root}/include"
  #create symlinks
  system("ln -fs #{path}/* .")
else
  puts "ERROR: root access required for installation" 
end
